name: Create release

on: 
  push:
    tags:
    - 'v*'

jobs:

  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/prepare_env
      - uses: ./.github/workflows/build
      - uses: ./.github/workflows/test
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.ttl"
          bodyFile: "build/release_note.md"