name: Compile package and test it

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Test output files in typical scenarios
        run: |
          python test/run_test.py